### ISSUE TITLE
to-do-list 작성(~8/18)

### ISSUE THREAD

**Issue by rootrue** [codestates/BEB-05-InnoBlue#5]
# Frontend Todo List
### Bare Minimum

- [ ]  Task 1: 헤더 생성 (이효정)
    - [ ]  웹페이지 로고를 누르면 메인 페이지로 돌아감
    - [ ]  회원가입/ 로그인, 로그아웃 버튼 만들기
        - [ ]  로그인을 했을 때 → 닉네임과 로그아웃 버튼 생김
        - [ ]  로그인을 하지 않았을 때 → ID/PW란과 로그인 및 회원가입 버튼이 있음
    - [ ]  마켓, 마이페이지 내비게이션
        - [ ]  ETH Faucet 버튼
- [ ]  Task 2: 메인 페이지 (랜딩 페이지) (이동현)
    - [ ]  게시글 리스트
        - [ ]  10페이지 단위씩 볼 수 있도록 페이지네이션으로 개발
        - [ ]  번호, 제목, 작성자, 생성일, 조회수가 보여야 함
        - [ ]  게시글 제목에 커서를 대면 커서가 누르는 모양으로 바뀌어야 함
        - [ ]  서버에서 게시글 리스트 데이터를 받아와야 함
    - [ ]  게시글 작성 버튼
        - [ ]  버튼을 누르면 게시글 작성 페이지로 이동함
- [ ]  Task 3: 게시글 작성 페이지 (이동현)
    - [ ]  리액트에서 제공하는 기본 폼으로 게시글 작성 페이지 개발
    - [ ]  제목, 내용 칸 있어야 함
    - [ ]  작성 버튼을 누르면, 제목과 내용이 글쓴이 아이디와 함께 서버로 전달해야 함
- [ ]  Task 4: 특정 게시글 조회 페이지
    - [ ]  번호, 제목, 작성자, 생성일, 조회수 등 정보가 있어야 함
    - [ ]  본문 있어야 함
    - [ ]  목록 버튼을 누르면 게시글 리스트의 클릭했던 목록으로 돌아감
- [ ]  Task 5: 회원가입 페이지 (이효정)
    - [ ]  React에서 제공하는 기본 폼으로 회원가입 페이지를 개발
        - [ ]  비밀번호 유효성 검사해야 함
    - [ ]  회원가입 버튼을 누르면 서버로 폼 데이터를 보내야 함
- [ ]  Task 6: 마이 페이지 (이효정)
    - [ ]  닉네임, 지갑 주소, 토큰 개수, 나의 NFT, 나의 게시글 정보를 볼 수 있어야 함
    - [ ]  타인에게 내가 가진 토큰을 줄 수 있는 칸이 있어야 함
- [ ]  Task 7: NFT 민팅 페이지
    - [ ]  사용자가 사진 주소를 올리면 민팅이 될 수 있어야 함
- [ ]  Task 8: 유저 정보 제어
    - [ ]  훅스, **리덕스**, 리코일 등 상태 관리를 통해 유저 정보를 제어할 수 있어야 함
- [ ]  Task 9: 마켓 페이지
    - [ ]  발행된 NFT를 볼 수 있어야 함?

### Recommended(권장)

- [ ]  HTTPS 설정
- [ ]  CSS 라이브러리 사용
- [ ]  푸터 생성 (Optional)
    - [ ]  팀 정보 및 깃헙 페이지 등 기본적인 정보
- [ ]  Not Found (Optional)
    - [ ]  사용자가 요청을 잘못 보냈을 때 해당 페이지 띄우기
- [ ]  Spinner (Optional)
    - [ ]  로딩이 길어졌을 때 흰색 화면 대신 해당 페이지 띄우기
- [ ]  기본 폼 이외에, 라이브러리 사용하여 개발
- [ ]  회원가입시 자동으로 로그인이 됨

### Advanced

- [ ]  게시글 작성시 태그 붙일 수 있음
- [ ]  NFT 상세 페이지 만들 수 있음
- [ ]  회원 탈퇴 가능
- [ ]  게시글 수정 및 삭제 가능
- [ ]  댓글 달 수 있음
- [ ]  게시글 검색 가능
- [ ]  마이페이지 수정 가능
- [ ]  로그인, 로그아웃 등 모달 생성
- [ ]  사용자가 NFT 판매 가능

# Backend Todo List
### Bare minimum

- [ ]  Task 1: NodeJS 서버 생성 (이혜인)
    - [x]  express를 사용하여 기본 서버 생성
    - [x] #19
    - [ ]  dotenv를 이용해 중요 정보 환경 변수 저장
- [ ]  Task 2: DB 연결 (김도영)
    - [ ]  서버와 연동
- [ ]  Task 3: 스마트 컨트랙트 연동 (이혜인)
    - [ ]  ABI 및 컨트랙트 주소로 web3.js 연동
- [ ]  Task 4: 필요한 API 작성
    - [ ]  Web3.js가 필요한 부분
        - [ ]  회원가입 API
            - [ ]  서버 계정 생성
        - [ ]  글 작성 시 보상토큰 지급받는 API
        - [ ]  유저간 토큰 전송 API
        - [ ]  특정 유저 정보 가져오는 API
        - [ ]  ETH Faucet 지급 받는 API
        - [ ]  NFT 구매를 위한 API
            - [ ]  유저 NFT 민팅
    - [ ]  Web3.js가 필요하지 않는 부분
        - [ ]  로그인 API
        - [ ]  게시판 GET API
        - [ ]  게시글 조회 GET API
- [ ]  Daemon 사용하여 트랜잭션 트래킹
    - [ ]  Daemon 설치
    - [ ]  Daemon 실행 후 확인

### Recommended

- [ ]  HTTPS 설정
- [ ]  DB ORM 라이브러리 이용하여 CRUD
- [ ]  회원가입/ 로그인 과정을 토큰을 이용하여 구현
- [ ]  Mint Multi Token 구현
